server:
  port: 10001

spring:
  application:
    name: gateway-server

eureka:
  client:
    service-url: http://localhost:10000/eureka/

zuul:
  routes:
    app-service:
      path: /api/app/*
      service-id: service-app
